# Generated by Django 4.0.3 on 2022-04-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_contributor_review_bookcontributor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
